"""adicionado o compo active na tabela store

Revision ID: 9da1495cbac6
Revises: eea4fb3a2ffa
Create Date: 2020-07-27 19:19:00.237649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da1495cbac6'
down_revision = 'eea4fb3a2ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'active')
    # ### end Alembic commands ###
