name: Python application
defaults:
  run:
    shell: bash
    working-directory: .

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make init_db

    - name: Databese Migrations
      run: |
        make init_db
        
    - name: Run tests
      run: |
        make test